
source = ~/.config/assets/palette/palette.conf

monitor=desc:Samsung Electric Company LC24RG50 HX5TA00390,1920x1080@143.98,auto,1

source = programs.conf
source = style.conf
source = input.conf
source = keys.conf
source = windows.conf
source = plugins.conf
source = wallpaper.conf
source = ~/.config/hypr/modules/animations/default.conf

env = WLR_NO_HARDWARE_CURSORS,1
#  env = WLR_RENDERER_ALLOW_SOFTWARE,1


